kind: pipeline
type: docker
name: clone-build-test

clone:
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
  - git clone https://github.com/quzhixue-Kimi/ddd-cargo-example.git ddd-cargo-example
  - pwd
  - ls
  - cd ddd-cargo-example
  - ls -la

- name: build
  image: maven:3.6.3-adoptopenjdk-8
  commands:
  - cd /drone/src/ddd-cargo-example
  - mvn clean package dockerfile:build dockerfile:push -DskipTests=true -Ddockerfile.maven.settings.auth=false -X -U
  - echo 'hello build'

- name: ping
  image: redis
  commands:
  - redis-cli -h cache ping

trigger:
  branch:
  - master
  event:
  - push

services:
  - name: cache
    image: redis