kind: pipeline
type: docker
name: clone-build-test

clone:
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
  - git clone https://github.com/quzhixue-Kimi/ddd-cargo-example.git ddd-cargo-example
  - pwd
  - ls
  - cd ddd-cargo-example
  - ls -la

- name: build
  image: maven:3.6.3-adoptopenjdk-8
  commands:
  - cd /drone/src/ddd-cargo-example
  - mvn clean package -DskipTests=true -Ddockerfile.maven.settings.auth=false -X -U
  - echo 'hello build'

- name: docker test
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start
  - docker ps -a

- name: ping
  image: redis
  commands:
  - redis-cli -h cache ping

trigger:
  branch:
  - master
  event:
  - push

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
    - name: dockersock
      path: /var/run
  - name: cache
    image: redis

volumes:
- name: dockersock
  temp: {}